services:
  - type: web
    name: backend-healthy
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3010